/* Generated By:JJTree: Do not edit this line. ASTBinaryOp.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package project;

public
class ASTBinaryOp extends SimpleNode {
  public ASTBinaryOp(int id) {
    super(id);
  }

  public ASTBinaryOp(CLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8779feb5445f83fda4eefdf2c8200643 (do not edit this line) */
