/* Generated By:JJTree: Do not edit this line. ASTCodeBlock.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package project;

public
class ASTCodeBlock extends SimpleNode {
  public ASTCodeBlock(int id) {
    super(id);
  }

  public ASTCodeBlock(CLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=930ed665593a7fa34e74e525b62addf8 (do not edit this line) */
