/* Generated By:JJTree: Do not edit this line. ASTIdentNode.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package project;

public
class ASTIdentNode extends SimpleNode {
  public ASTIdentNode(int id) {
    super(id);
  }

  public ASTIdentNode(CLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3b710c36c27887128516a1e538f24a09 (do not edit this line) */
