/* Generated By:JJTree: Do not edit this line. ASTLoopStmt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package project;

public
class ASTLoopStmt extends SimpleNode {
  public ASTLoopStmt(int id) {
    super(id);
  }

  public ASTLoopStmt(CLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9ea31a956a2219506b022448fec6ac2f (do not edit this line) */
