/* Generated By:JJTree: Do not edit this line. ASTOutStringStmt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package project;

public
class ASTOutStringStmt extends SimpleNode {
  public ASTOutStringStmt(int id) {
    super(id);
  }

  public ASTOutStringStmt(CLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0385ff2c9f3f7986995b8bccc5053e19 (do not edit this line) */
