/* Generated By:JJTree: Do not edit this line. ASTOtherClause.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package project;

public
class ASTOtherClause extends SimpleNode {
  public ASTOtherClause(int id) {
    super(id);
  }

  public ASTOtherClause(CLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=abf310e537b8adeb0c7b410431274b1b (do not edit this line) */
