/* Generated By:JJTree: Do not edit this line. ASTSwitchStmt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package project;

public
class ASTSwitchStmt extends SimpleNode {
  public ASTSwitchStmt(int id) {
    super(id);
  }

  public ASTSwitchStmt(CLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3304012e4d607be73762bc220ec0e113 (do not edit this line) */
