/* Generated By:JJTree: Do not edit this line. ASTUnaryOp.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package project;

public
class ASTUnaryOp extends SimpleNode {
  public ASTUnaryOp(int id) {
    super(id);
  }

  public ASTUnaryOp(CLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=20aa91f95e08d286b63cac624f9f4206 (do not edit this line) */
