/* Generated By:JJTree: Do not edit this line. ASTVarBlock.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package project;

public
class ASTVarBlock extends SimpleNode {
  public ASTVarBlock(int id) {
    super(id);
  }

  public ASTVarBlock(CLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=86a4a1d1092e82678179cc3d69be8a29 (do not edit this line) */
