/* Generated By:JJTree&JavaCC: Do not edit this line. CLParserConstants.java */
package project;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 5;
  /** RegularExpression Id. */
  int STARTPROGRAM = 6;
  /** RegularExpression Id. */
  int ENDPROGRAM = 7;
  /** RegularExpression Id. */
  int VARIABLES = 8;
  /** RegularExpression Id. */
  int CODE = 9;
  /** RegularExpression Id. */
  int INT = 10;
  /** RegularExpression Id. */
  int FLOAT = 11;
  /** RegularExpression Id. */
  int STRING_TYPE = 12;
  /** RegularExpression Id. */
  int CHAR_TYPE = 13;
  /** RegularExpression Id. */
  int LOOPIF = 14;
  /** RegularExpression Id. */
  int HOLDS = 15;
  /** RegularExpression Id. */
  int ENDLOOP = 16;
  /** RegularExpression Id. */
  int SWITCHFOR = 17;
  /** RegularExpression Id. */
  int CASE = 18;
  /** RegularExpression Id. */
  int OTHER = 19;
  /** RegularExpression Id. */
  int ENDSWITCHFOR = 20;
  /** RegularExpression Id. */
  int OUTSTRING = 21;
  /** RegularExpression Id. */
  int ASSIGN = 22;
  /** RegularExpression Id. */
  int PLUS = 23;
  /** RegularExpression Id. */
  int MINUS = 24;
  /** RegularExpression Id. */
  int TIMES = 25;
  /** RegularExpression Id. */
  int DIVIDE = 26;
  /** RegularExpression Id. */
  int SEMI = 27;
  /** RegularExpression Id. */
  int COLON = 28;
  /** RegularExpression Id. */
  int LPAREN = 29;
  /** RegularExpression Id. */
  int RPAREN = 30;
  /** RegularExpression Id. */
  int LE = 31;
  /** RegularExpression Id. */
  int GE = 32;
  /** RegularExpression Id. */
  int EQ = 33;
  /** RegularExpression Id. */
  int NEQ = 34;
  /** RegularExpression Id. */
  int LT = 35;
  /** RegularExpression Id. */
  int GT = 36;
  /** RegularExpression Id. */
  int INTEGER_LIT = 37;
  /** RegularExpression Id. */
  int FLOAT_LIT = 38;
  /** RegularExpression Id. */
  int CHAR_LIT = 39;
  /** RegularExpression Id. */
  int STRING_LIT = 40;
  /** RegularExpression Id. */
  int IDENTIFIER = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<COMMENT>",
    "\"startProgram\"",
    "\"endProgram\"",
    "\"variables:\"",
    "\"code:\"",
    "\"int\"",
    "\"float\"",
    "\"string\"",
    "\"char\"",
    "\"loopif\"",
    "\"holds\"",
    "\"endloop\"",
    "\"switchFor\"",
    "\"case\"",
    "\"other\"",
    "\"endswitchFor\"",
    "\"outString\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\";\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"<>\"",
    "\"<\"",
    "\">\"",
    "<INTEGER_LIT>",
    "<FLOAT_LIT>",
    "<CHAR_LIT>",
    "<STRING_LIT>",
    "<IDENTIFIER>",
  };

}
