/* Generated By:JavaCC: Do not edit this line. CLParserTreeConstants.java Version 7.0.12 */
package project;

public interface CLParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVARBLOCK = 1;
  public int JJTVARDECL = 2;
  public int JJTVOID = 3;
  public int JJTCODEBLOCK = 4;
  public int JJTASSIGNSTMT = 5;
  public int JJTLOOPSTMT = 6;
  public int JJTSWITCHSTMT = 7;
  public int JJTCASECLAUSE = 8;
  public int JJTOTHERCLAUSE = 9;
  public int JJTOUTSTRINGSTMT = 10;
  public int JJTCONDEXPR = 11;
  public int JJTLITERAL = 12;
  public int JJTIDENTNODE = 13;
  public int JJTBINARYOP = 14;
  public int JJTUNARYOP = 15;


  public String[] jjtNodeName = {
    "Program",
    "VarBlock",
    "VarDecl",
    "void",
    "CodeBlock",
    "AssignStmt",
    "LoopStmt",
    "SwitchStmt",
    "CaseClause",
    "OtherClause",
    "OutStringStmt",
    "CondExpr",
    "Literal",
    "IdentNode",
    "BinaryOp",
    "UnaryOp",
  };
}
/* JavaCC - OriginalChecksum=04a28a84f3d22719e844075e90fc26b2 (do not edit this line) */
