/* Generated By:JavaCC: Do not edit this line. CLParserVisitor.java Version 7.0.12 */
package project;

public interface CLParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTVarBlock node, Object data);
  public Object visit(ASTVarDecl node, Object data);
  public Object visit(ASTCodeBlock node, Object data);
  public Object visit(ASTAssignStmt node, Object data);
  public Object visit(ASTLoopStmt node, Object data);
  public Object visit(ASTSwitchStmt node, Object data);
  public Object visit(ASTCaseClause node, Object data);
  public Object visit(ASTOtherClause node, Object data);
  public Object visit(ASTOutStringStmt node, Object data);
  public Object visit(ASTCondExpr node, Object data);
  public Object visit(ASTLiteral node, Object data);
  public Object visit(ASTIdentNode node, Object data);
  public Object visit(ASTBinaryOp node, Object data);
  public Object visit(ASTUnaryOp node, Object data);
}
/* JavaCC - OriginalChecksum=9eecfc8ba7b0564bb92a2845195a7eaf (do not edit this line) */
