/* CLParser.java */
/* Generated By:JJTree&JavaCC: Do not edit this line. CLParser.java */
package project;

import java.io.*;

public class CLParser/*@bgen(jjtree)*/implements CLParserTreeConstants, CLParserConstants {/*@bgen(jjtree)*/
  protected JJTCLParserState jjtree = new JJTCLParserState();
    public static void main(String[] args) throws Exception {
        Reader input;
        if (args.length > 0) {
            input = new FileReader(args[0]);
        } else {
            System.out.println("CL Compiler \u2014 reading from stdin (type program, then EOF):");
            input = new InputStreamReader(System.in);
        }

        CLParser parser = new CLParser(input);
        try {
            SimpleNode root = parser.Program();

            System.out.println("\n====== SYMBOL TABLE ======");
            SymbolTable symTable = new SymbolTable();
            SemanticAnalyzer semAnalyzer = new SemanticAnalyzer(symTable);
            semAnalyzer.analyze(root);
            symTable.print();

            System.out.println("\n====== INTERMEDIATE CODE (Quadruples) ======");
            IRGenerator irGen = new IRGenerator(symTable);
            irGen.generate(root);
            irGen.printQuadruples();

            System.out.println("\n------ IR Statements ------");
            irGen.printStatements();

            System.out.println("\n====== OPTIMIZED IR ======");
            Optimizer optimizer = new Optimizer(irGen.getQuadruples());
            optimizer.optimize();
            optimizer.printQuadruples();

            System.out.println("\n------ Optimized IR Statements ------");
            optimizer.printStatements();

            System.out.println("\n====== TARGET ASSEMBLY CODE ======");
            CodeGenerator codeGen = new CodeGenerator(optimizer.getQuadruples());
            codeGen.generate();
            codeGen.printAssembly();

        } catch (ParseException e) {
            System.err.println("Syntax Error: " + e.getMessage());
        } catch (SemanticException e) {
            System.err.println("Semantic Error: " + e.getMessage());
        }
    }

/* ============================================================
   GRAMMAR RULES
   ============================================================ */

/** Root production */
  final public 
SimpleNode Program() throws ParseException {/*@bgen(jjtree) Program */
  ASTProgram jjtn000 = new ASTProgram(JJTPROGRAM);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(STARTPROGRAM);
      VarBlock();
      CodeBlock();
      jj_consume_token(ENDPROGRAM);
      jj_consume_token(0);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return jjtn000;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  final public void VarBlock() throws ParseException {/*@bgen(jjtree) VarBlock */
  ASTVarBlock jjtn000 = new ASTVarBlock(JJTVARBLOCK);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(VARIABLES);
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case INT:
        case FLOAT:
        case STRING_TYPE:
        case CHAR_TYPE:{
          ;
          break;
          }
        default:
          jj_la1[0] = jj_gen;
          break label_1;
        }
        VarDecl();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void VarDecl() throws ParseException {/*@bgen(jjtree) VarDecl */
  ASTVarDecl jjtn000 = new ASTVarDecl(JJTVARDECL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t, id;
    try {
      t = TypeToken();
      id = jj_consume_token(IDENTIFIER);
jjtn000.jjtSetValue(t.image + " " + id.image);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ASSIGN:{
        jj_consume_token(ASSIGN);
        Literal();
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        ;
      }
      jj_consume_token(SEMI);
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public Token TypeToken() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:{
      t = jj_consume_token(INT);
      break;
      }
    case FLOAT:{
      t = jj_consume_token(FLOAT);
      break;
      }
    case STRING_TYPE:{
      t = jj_consume_token(STRING_TYPE);
      break;
      }
    case CHAR_TYPE:{
      t = jj_consume_token(CHAR_TYPE);
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return t;}
    throw new Error("Missing return statement in function");
}

  final public void CodeBlock() throws ParseException {/*@bgen(jjtree) CodeBlock */
  ASTCodeBlock jjtn000 = new ASTCodeBlock(JJTCODEBLOCK);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(CODE);
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LOOPIF:
        case SWITCHFOR:
        case OUTSTRING:
        case IDENTIFIER:{
          ;
          break;
          }
        default:
          jj_la1[3] = jj_gen;
          break label_2;
        }
        Statement();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void Statement() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFIER:{
      AssignStatement();
      break;
      }
    case LOOPIF:{
      LoopStatement();
      break;
      }
    case SWITCHFOR:{
      SwitchStatement();
      break;
      }
    case OUTSTRING:{
      OutStringStatement();
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void AssignStatement() throws ParseException {/*@bgen(jjtree) AssignStmt */
  ASTAssignStmt jjtn000 = new ASTAssignStmt(JJTASSIGNSTMT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token id;
    try {
      id = jj_consume_token(IDENTIFIER);
jjtn000.jjtSetValue(id.image);
      jj_consume_token(ASSIGN);
      Expression();
      jj_consume_token(SEMI);
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void LoopStatement() throws ParseException {/*@bgen(jjtree) LoopStmt */
  ASTLoopStmt jjtn000 = new ASTLoopStmt(JJTLOOPSTMT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(LOOPIF);
      CondExpression();
      jj_consume_token(HOLDS);
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDENTIFIER:{
          ;
          break;
          }
        default:
          jj_la1[5] = jj_gen;
          break label_3;
        }
        AssignStatement();
      }
      jj_consume_token(ENDLOOP);
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void SwitchStatement() throws ParseException {/*@bgen(jjtree) SwitchStmt */
  ASTSwitchStmt jjtn000 = new ASTSwitchStmt(JJTSWITCHSTMT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token id;
    try {
      jj_consume_token(SWITCHFOR);
      jj_consume_token(LPAREN);
      id = jj_consume_token(IDENTIFIER);
jjtn000.jjtSetValue(id.image);
      jj_consume_token(RPAREN);
      label_4:
      while (true) {
        CaseClause();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case CASE:{
          ;
          break;
          }
        default:
          jj_la1[6] = jj_gen;
          break label_4;
        }
      }
      OtherClause();
      jj_consume_token(ENDSWITCHFOR);
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void CaseClause() throws ParseException {/*@bgen(jjtree) CaseClause */
  ASTCaseClause jjtn000 = new ASTCaseClause(JJTCASECLAUSE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(CASE);
      Literal();
      jj_consume_token(COLON);
      AssignStatement();
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void OtherClause() throws ParseException {/*@bgen(jjtree) OtherClause */
  ASTOtherClause jjtn000 = new ASTOtherClause(JJTOTHERCLAUSE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(OTHER);
      jj_consume_token(COLON);
      AssignStatement();
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void OutStringStatement() throws ParseException {/*@bgen(jjtree) OutStringStmt */
  ASTOutStringStmt jjtn000 = new ASTOutStringStmt(JJTOUTSTRINGSTMT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(OUTSTRING);
      jj_consume_token(LPAREN);
      Expression();
      jj_consume_token(RPAREN);
      jj_consume_token(SEMI);
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void CondExpression() throws ParseException {/*@bgen(jjtree) CondExpr */
  ASTCondExpr jjtn000 = new ASTCondExpr(JJTCONDEXPR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token op;
    try {
      Expression();
      op = CondOp();
jjtn000.jjtSetValue(op.image);
      Expression();
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public Token CondOp() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LE:{
      t = jj_consume_token(LE);
      break;
      }
    case GE:{
      t = jj_consume_token(GE);
      break;
      }
    case EQ:{
      t = jj_consume_token(EQ);
      break;
      }
    case NEQ:{
      t = jj_consume_token(NEQ);
      break;
      }
    case LT:{
      t = jj_consume_token(LT);
      break;
      }
    case GT:{
      t = jj_consume_token(GT);
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return t;}
    throw new Error("Missing return statement in function");
}

/* Expression with precedence: + and - */
  final public void Expression() throws ParseException {
    Term();
    ExprRest();
}

  final public void ExprRest() throws ParseException {Token op;
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:{
        ;
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        break label_5;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        op = jj_consume_token(PLUS);
        Term();
SimpleNode right = (SimpleNode) jjtree.popNode();
                          SimpleNode left  = (SimpleNode) jjtree.popNode();
                          ASTBinaryOp n = new ASTBinaryOp(JJTBINARYOP);
                          n.jjtSetValue(op.image);
                          n.jjtAddChild(left,  0); left.jjtSetParent(n);
                          n.jjtAddChild(right, 1); right.jjtSetParent(n);
                          jjtree.pushNode(n);
        break;
        }
      case MINUS:{
        op = jj_consume_token(MINUS);
        Term();
SimpleNode right = (SimpleNode) jjtree.popNode();
                          SimpleNode left  = (SimpleNode) jjtree.popNode();
                          ASTBinaryOp n = new ASTBinaryOp(JJTBINARYOP);
                          n.jjtSetValue(op.image);
                          n.jjtAddChild(left,  0); left.jjtSetParent(n);
                          n.jjtAddChild(right, 1); right.jjtSetParent(n);
                          jjtree.pushNode(n);
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

/* Term: * and / */
  final public void Term() throws ParseException {
    Factor();
    TermRest();
}

  final public void TermRest() throws ParseException {Token op;
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TIMES:
      case DIVIDE:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_6;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TIMES:{
        op = jj_consume_token(TIMES);
        Factor();
SimpleNode right = (SimpleNode) jjtree.popNode();
                              SimpleNode left  = (SimpleNode) jjtree.popNode();
                              ASTBinaryOp n = new ASTBinaryOp(JJTBINARYOP);
                              n.jjtSetValue(op.image);
                              n.jjtAddChild(left,  0); left.jjtSetParent(n);
                              n.jjtAddChild(right, 1); right.jjtSetParent(n);
                              jjtree.pushNode(n);
        break;
        }
      case DIVIDE:{
        op = jj_consume_token(DIVIDE);
        Factor();
SimpleNode right = (SimpleNode) jjtree.popNode();
                              SimpleNode left  = (SimpleNode) jjtree.popNode();
                              ASTBinaryOp n = new ASTBinaryOp(JJTBINARYOP);
                              n.jjtSetValue(op.image);
                              n.jjtAddChild(left,  0); left.jjtSetParent(n);
                              n.jjtAddChild(right, 1); right.jjtSetParent(n);
                              jjtree.pushNode(n);
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

  final public void Factor() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFIER:{
      t = jj_consume_token(IDENTIFIER);
ASTIdentNode n = new ASTIdentNode(JJTIDENTNODE);
                        n.jjtSetValue(t.image); jjtree.pushNode(n);
      break;
      }
    case INTEGER_LIT:
    case FLOAT_LIT:
    case CHAR_LIT:
    case STRING_LIT:{
      Literal();
      break;
      }
    case LPAREN:{
      jj_consume_token(LPAREN);
      Expression();
      jj_consume_token(RPAREN);
      break;
      }
    case MINUS:{
      jj_consume_token(MINUS);
      Factor();
SimpleNode operand = (SimpleNode) jjtree.popNode();
                               ASTUnaryOp n = new ASTUnaryOp(JJTUNARYOP);
                               n.jjtSetValue("minus");
                               n.jjtAddChild(operand, 0); operand.jjtSetParent(n);
                               jjtree.pushNode(n);
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void Literal() throws ParseException {/*@bgen(jjtree) Literal */
  ASTLiteral jjtn000 = new ASTLiteral(JJTLITERAL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INTEGER_LIT:{
        t = jj_consume_token(INTEGER_LIT);
        break;
        }
      case FLOAT_LIT:{
        t = jj_consume_token(FLOAT_LIT);
        break;
        }
      case STRING_LIT:{
        t = jj_consume_token(STRING_LIT);
        break;
        }
      case CHAR_LIT:{
        t = jj_consume_token(CHAR_LIT);
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.jjtSetValue(t.image);
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

/* ============================================================
   Extra AST node IDs (referenced in Factor inline nodes)
   ============================================================ */
  final public void IdentNode() throws ParseException {/*@bgen(jjtree) IdentNode */
  ASTIdentNode jjtn000 = new ASTIdentNode(JJTIDENTNODE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(IDENTIFIER);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.jjtSetValue(t.image);
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void BinaryOp() throws ParseException {/*@bgen(jjtree) BinaryOp */
  ASTBinaryOp jjtn000 = new ASTBinaryOp(JJTBINARYOP);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token op;
    try {
      op = jj_consume_token(PLUS);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.jjtSetValue(op.image);
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void UnaryOp() throws ParseException {/*@bgen(jjtree) UnaryOp */
  ASTUnaryOp jjtn000 = new ASTUnaryOp(JJTUNARYOP);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;

    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  /** Generated Token Manager. */
  public CLParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[14];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x3c00,0x400000,0x3c00,0x224000,0x224000,0x0,0x40000,0x80000000,0x1800000,0x1800000,0x6000000,0x6000000,0x21000000,0x0,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x0,0x0,0x200,0x200,0x200,0x0,0x1f,0x0,0x0,0x0,0x0,0x3e0,0x1e0,};
	}

  /** Constructor with InputStream. */
  public CLParser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public CLParser(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new CLParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public CLParser(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new CLParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new CLParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public CLParser(CLParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(CLParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[42];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 14; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 42; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
