/* Generated By:JavaCC: Do not edit this line. CLParserDefaultVisitor.java Version 7.0.12 */
package project;

public class CLParserDefaultVisitor implements CLParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTProgram node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTVarBlock node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTVarDecl node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCodeBlock node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAssignStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLoopStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTSwitchStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCaseClause node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOtherClause node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOutStringStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCondExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLiteral node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIdentNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBinaryOp node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTUnaryOp node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=214f37350471e41a1697703391e21148 (do not edit this line) */
